import { NgModule } from '@angular/core'
import {
    MdButtonModule,
    MdCheckboxModule,
    MdAutocompleteModule,
    MdCardModule,
    MdChipsModule,
    MdDialogModule,
    MdIconModule,
    MdInputModule,
    MdCoreModule,
    MdButtonToggleModule,
    MdListModule,
    MdMenuModule,
    MdRadioModule,
    MdRippleModule,
    MdSelectModule,
    MdSidenavModule,
    MdSnackBarModule,
    MdTabsModule,
    MdToolbarModule,
    MdTooltipModule,
    OverlayModule,
    ObserveContentModule
} from '@angular/material';

@NgModule({
    imports: [
        MdButtonModule,
        MdCheckboxModule,
        MdAutocompleteModule,
        MdCardModule,
        MdChipsModule,
        MdDialogModule,
        MdIconModule,
        MdInputModule,
        MdCoreModule,
        MdButtonToggleModule,
        MdListModule,
        MdMenuModule,
        MdRadioModule,
        MdRippleModule,
        MdSelectModule,
        MdSidenavModule,
        MdSnackBarModule,
        MdTabsModule,
        MdToolbarModule,
        MdTooltipModule,
        OverlayModule,
        ObserveContentModule
    ],
    exports: [
        MdButtonModule,
        MdCheckboxModule,
        MdAutocompleteModule,
        MdCardModule,
        MdChipsModule,
        MdDialogModule,
        MdIconModule,
        MdInputModule,
        MdCoreModule,
        MdButtonToggleModule,
        MdListModule,
        MdMenuModule,
        MdRadioModule,
        MdRippleModule,
        MdSelectModule,
        MdSidenavModule,
        MdSnackBarModule,
        MdTabsModule,
        MdToolbarModule,
        MdTooltipModule,
        OverlayModule,
        ObserveContentModule
    ]
})
export class AppMaterialModule { }